task_manager/api/urls.py
from django.urls import path
from task_manager.api.users import views


urlpatterns = [
    path('users/', views.UserAPIView.as_view(), name='user-list'),
]

task_manager/tasks/urls.py
from django.urls import path
from task_manager.tasks import views


app_name = 'tasks'


urlpatterns = [
    path('', views.TasksView.as_view(), name='tasks'),
    path('create/', views.CreateTaskView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateTaskView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteTaskView.as_view(), name='delete'),
    path('<int:pk>/', views.DetailTaskView.as_view(), name='task'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
# from rest_framework import routers
from task_manager import views


# router = routers.DefaultRouter()
#
# router.register()

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('users/', include('task_manager.users.urls', namespace='users')),
    path('statuses/', include('task_manager.statuses.urls', namespace='statuses')),
    path('tasks/', include('task_manager.tasks.urls', namespace='tasks')),
    path('labels/', include('task_manager.labels.urls', namespace='labels')),
    path('api/v1/', include('task_manager.api.urls')),
    path('admin/', admin.site.urls),
]

task_manager/users/urls.py
from django.urls import path
from task_manager.users import views


app_name = 'users'


urlpatterns = [
    path('', views.UsersView.as_view(), name='users'),
    path('create/', views.CreateUserView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateUserView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteUserView.as_view(), name='delete'),
]

task_manager/labels/models.py
from django.db import models


class Label(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/statuses/models.py
from django.db import models


class Status(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/tasks/models.py
from django.db import models
from django.conf import settings
from task_manager.statuses.models import Status
from task_manager.labels.models import Label


class Task(models.Model):
    name = models.CharField(max_length=150, unique=True)
    description = models.TextField(blank=True)
    executor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        null=True, blank=True
    )
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name='tasks'
    )
    labels = models.ManyToManyField(Label, through='TaskLabel', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TaskLabel(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    labels = models.ForeignKey(Label, on_delete=models.PROTECT)

task_manager/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    def __str__(self):
        return self.get_full_name()

task_manager/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm


class LoginUserForm(AuthenticationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']

task_manager/labels/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from task_manager.labels.models import Label


class LabelCreateForm(forms.ModelForm):

    class Meta:
        model = Label
        fields = ['name']

    name = forms.CharField(
        label=_('Name'),
        max_length=100
    )

task_manager/statuses/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from task_manager.statuses.models import Status


class StatusCreateForm(forms.ModelForm):

    class Meta:
        model = Status
        fields = ['name']

    name = forms.CharField(
        label=_('Name'),
        max_length=100
    )

task_manager/tasks/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from task_manager.tasks.models import Task
from django.contrib.auth import get_user_model
from task_manager.statuses.models import Status
from task_manager.labels.models import Label


class TaskCreateForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'executor', 'labels']

    name = forms.CharField(
        label=_('Name'),
        max_length=150,
    )

    description = forms.CharField(
        label=_('Description'),
        widget=forms.Textarea()
    )

    status = forms.ModelChoiceField(
        queryset=Status.objects.all(),
        label=_('Status'),
    )
    executor = forms.ModelChoiceField(
        queryset=get_user_model().objects.all(),
        label=_('Executor'),
        required=False
    )
    labels = forms.ModelMultipleChoiceField(
        queryset=Label.objects.all(),
        label=_('Labels'),
        required=False
    )

task_manager/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class UserCreateForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'username']

task_manager/api/users/views.py
from rest_framework import generics
from django.contrib.auth import get_user_model
from task_manager.api.users.serializers import UserSerializer


class UserAPIView(generics.ListAPIView):
    """
    API view for retrieving a list of users.

    This view extends the generics.ListAPIView class
    provided by Django Rest Framework (DRF).
    """
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer

task_manager/labels/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, CreateView,
    UpdateView, DeleteView)
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _
from task_manager.mixins import AuthRequiredMixin, DeletionProtectHandleMixin
from task_manager.labels.models import Label
from task_manager.labels.forms import LabelCreateForm


class LabelsView(AuthRequiredMixin, ListView):
    model = Label
    template_name = 'labels/labels.html'
    context_object_name = 'labels'
    ordering = ['pk']


class CreateLabelView(SuccessMessageMixin, AuthRequiredMixin, CreateView):
    model = Label
    form_class = LabelCreateForm
    template_name = 'labels/create.html'
    success_url = reverse_lazy('labels:labels')
    success_message = _('Label has been successfully created')


class UpdateLabelView(SuccessMessageMixin, AuthRequiredMixin, UpdateView):
    model = Label
    form_class = LabelCreateForm
    template_name = 'labels/update.html'
    success_url = reverse_lazy('labels:labels')
    success_message = _('Label has been successfully changed')


class DeleteLabelView(SuccessMessageMixin,
                      AuthRequiredMixin,
                      DeletionProtectHandleMixin,
                      DeleteView):
    model = Label
    template_name = 'labels/delete.html'
    success_url = redirect_url = reverse_lazy('labels:labels')
    success_message = _('Label has been successfully deleted')
    protection_msg = _("Label can't be deleted. It is linked to one or more tasks")

task_manager/statuses/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from task_manager.statuses.models import Status
from task_manager.statuses.forms import StatusCreateForm
from task_manager.mixins import AuthRequiredMixin, DeletionProtectHandleMixin


class StatusesView(AuthRequiredMixin, ListView):
    model = Status
    template_name = 'statuses/statuses.html'
    context_object_name = 'statuses'
    ordering = ['pk']


class CreateStatusView(SuccessMessageMixin, AuthRequiredMixin, CreateView):
    model = Status
    form_class = StatusCreateForm
    template_name = 'statuses/create.html'
    success_url = reverse_lazy('statuses:statuses')
    success_message = _('Status has been successfully created')


class UpdateStatusView(SuccessMessageMixin, AuthRequiredMixin, UpdateView):
    model = Status
    form_class = StatusCreateForm
    template_name = 'statuses/update.html'
    success_url = reverse_lazy('statuses:statuses')
    success_message = _('Status has been successfully changed')


class DeleteStatusView(SuccessMessageMixin,
                       AuthRequiredMixin,
                       DeletionProtectHandleMixin,
                       DeleteView):
    model = Status
    template_name = 'statuses/delete.html'
    success_url = redirect_url = reverse_lazy('statuses:statuses')
    success_message = _('Status has been successfully deleted')
    protection_msg = _("Status can't be deleted. It is linked to one or more tasks")

task_manager/tasks/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView, DetailView,
    UpdateView, DeleteView
)
from task_manager.tasks.models import Task
from task_manager.tasks.forms import TaskCreateForm
from task_manager.mixins import (
    AuthRequiredMixin,
    AuthorPermissionMixin
)
from django_filters.views import FilterView
from task_manager.tasks.filters import TasksFilter
from django.contrib.auth import get_user_model


class TasksView(AuthRequiredMixin, FilterView):
    model = Task
    template_name = 'tasks/tasks.html'
    context_object_name = 'tasks'
    ordering = ['pk']
    filterset_class = TasksFilter


class DetailTaskView(AuthRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/task.html'
    context_object_name = 'task'


class CreateTaskView(AuthRequiredMixin, SuccessMessageMixin, CreateView):
    model = Task
    form_class = TaskCreateForm
    template_name = 'tasks/create.html'
    success_url = reverse_lazy('tasks:tasks')
    success_message = _('Task has been successfully created')

    def form_valid(self, form):
        user = self.request.user
        form.instance.author = get_user_model().objects.get(pk=user.pk)
        return super().form_valid(form)


class UpdateTaskView(AuthRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Task
    form_class = TaskCreateForm
    template_name = 'tasks/update.html'
    success_url = reverse_lazy('tasks:tasks')
    success_message = _('Task has been successfully changed')


class DeleteTaskView(AuthRequiredMixin,
                     AuthorPermissionMixin,
                     SuccessMessageMixin,
                     DeleteView):
    model = Task
    template_name = 'tasks/delete.html'
    success_url = reverse_lazy('tasks:tasks')
    success_message = _('Task has been successfully deleted')

task_manager/users/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from task_manager.users.forms import UserCreateForm
from task_manager.mixins import (AuthRequiredMixin,
                                 UserPermissionMixin,
                                 DeletionProtectHandleMixin)


class UsersView(ListView):
    model = get_user_model()
    template_name = 'users/users.html'
    context_object_name = 'users'
    ordering = ['pk']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['request'] = self.request
        return context


class CreateUserView(SuccessMessageMixin, CreateView):
    form_class = UserCreateForm
    template_name = 'users/create.html'
    success_url = reverse_lazy('login')
    success_message = _('User has been successfully registered')


class UpdateUserView(AuthRequiredMixin,
                     UserPermissionMixin,
                     SuccessMessageMixin,
                     UpdateView):
    model = get_user_model()
    form_class = UserCreateForm
    template_name = 'users/update.html'
    success_url = reverse_lazy('users:users')
    success_message = _('User has been successfully changed')


class DeleteUserView(AuthRequiredMixin,
                     UserPermissionMixin,
                     DeletionProtectHandleMixin,
                     SuccessMessageMixin,
                     DeleteView):
    model = get_user_model()
    template_name = 'users/delete.html'
    success_url = redirect_url = reverse_lazy('users:users')
    success_message = _('User has been successfully deleted')
    protection_msg = _("User can't be deleted. It is linked to one or more tasks")

task_manager/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _
from task_manager.forms import LoginUserForm


class IndexView(TemplateView):
    template_name = 'index.html'


class LoginUserView(SuccessMessageMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'login.html'
    success_message = _("You've successfully logged in")


class LogoutUserView(LogoutView):

    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        messages.info(request, _("You've successfully logged out"))
        return response

task_manager/templates/users/create.html
{% extends "layout.html" %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block title %}
{% translate "Registration" %}
{% endblock %}

{% block content %}
<div class="container wrapper flex-grow-1">
    <h1 class="my-4"></h1>
    <div class="row d-flex justify-content-center">
        <div class="col-12 col-md-9 col-lg-6 px-4 border rounded bg-light">
            <div class="my-3">
            </div>
            <h1 class="my-3">
                {% block heading %}
                {% translate "Registration" %}
                {% endblock %}
            </h1>
            {% block form %}
            <form action="{% url 'users:create' %}" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}

                {% translate "Register" as button_name %}
                {% bootstrap_button button_type="submit" button_class="btn-warning mb-4" content=button_name %}
            {% endblock %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

task_manager/templates/users/delete.html
{% extends "components/delete.html" %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block title %}
{% translate "Delete user" %}
{% endblock %}

{% block heading %}
{% translate "Deleting the user" %}
{% endblock %}

{% block text %}
{% translate "Are you sure you want to delete" %} {{ user.first_name }} {{ user.last_name }}
{% endblock %}

{% block form %}
<form action="{% url 'users:delete' pk=user.pk %}" method="post" class="form">
  {% csrf_token %}

  {% translate "Yes, delete" as button_name %}
  {% bootstrap_button button_type="submit" button_class="btn-danger mb-4" content=button_name %}
</form>
{% endblock %}

task_manager/templates/users/update.html
{% extends "users/create.html" %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block title %}
{% translate "Update user" %}
{% endblock %}

{% block heading %}
{% translate "User changing" %}
{% endblock %}

{% block form %}
<form action="{% url 'users:update' pk=user.pk %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% translate "Change" as button_name %}
    {% bootstrap_button button_type="submit" button_class="btn-warning mb-4" content=button_name %}
</form>
{% endblock %}

task_manager/templates/users/users.html
{% extends "layout.html" %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block title %}
{% translate "Users" %}
{% endblock %}

{% block content %}
<main class="container flex-grow-1">
    <div class="mt-4">
        {% bootstrap_messages %}
    </div>
    <h1 class="my-4"></h1>
    <h2>{% translate "Users" %}</h2>
    <div class="row">
        <div class="col">
            <div class="table-responsive">
                <table class="table">
                    <caption>{% translate "List of users" %}</caption>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>{% translate "Username" %}</th>
                            <th>{% translate "Full name" %}</th>
                            <th>{% translate "Date of creation" %}</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% if user.is_authenticated %}
                    {% for user in users %}
                        {% translate "Current user" as value %}
                        <tr {% if user.is_authenticated and user.username == request.user.username %}class="text-warning" title="{{ value }}" {% endif %}>
                            <td>{{ user.id }}</td>
                            <td>{{ user.username }}</td>
                            <td>{{ user.get_full_name }}</td>
                            <td>{{ user.date_joined|date:'d.m.Y H:i' }}</td>
                            <td>
                                <a href="{% url 'users:update' pk=user.pk %}" class="text-decoration-none">{% translate "Edit" %}</a>
                                <br>
                                <a href="{% url 'users:delete' pk=user.pk %}" class="text-decoration-none">{% translate "Delete" %}</a>
                            </td>
                        </tr>
                    {% endfor %}

                    {% else %}

                    {% for user in users %}
                        <tr>
                            <td>{{ user.id }}</td>
                            <td>{{ user.username }}</td>
                            <td>{{ user.get_full_name }}</td>
                            <td>{{ user.date_joined|date:'d.m.Y H:i' }}</td>
                            <td>
                                <a href="{% url 'users:update' pk=user.pk %}" class="text-decoration-none text-muted">{% translate "Edit" %}</a>
                                <br>
                                <a href="{% url 'users:delete' pk=user.pk %}" class="text-decoration-none text-muted">{% translate "Delete" %}</a>
                            </td>
                        </tr>
                    {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
             </div>
        </div>
    </div>
</main>
{% endblock %}